export const blogPosts = [
  { slug: 'house-construction-cost-kerala', title: 'House Construction Cost in Kerala (2024 Guide)', excerpt: 'Understand the current market rates and material costs for building a home.', category: 'Guides' },
  { slug: 'budget-planning-home-construction', title: 'Budget Planning for Home Construction', excerpt: 'Manage your finances and avoid common pitfalls during the building process.', category: 'Finance' },
  { slug: 'best-time-start-construction', title: 'Best Time to Start House Construction', excerpt: 'Planning your project around the Kerala monsoon and labor availability.', category: 'Planning' },
  { slug: 'modern-house-design-trends', title: 'Modern House Design Trends in Kerala', excerpt: 'Exploring the rise of boxy homes and minimalist interiors.', category: 'Design' },
  { slug: 'construction-timeline-guide', title: 'Construction Timeline for Building a House', excerpt: 'A step-by-step breakdown from foundation to key handover.', category: 'Process' },
  { slug: 'choose-best-construction-company', title: 'How to Choose the Best Construction Company', excerpt: 'Critical factors to consider before signing a contract.', category: 'Guides' },
  { slug: 'common-construction-mistakes', title: 'Common House Construction Mistakes', excerpt: 'Avoid these costly errors when building your dream home.', category: 'Expertise' },
  { slug: 'transparent-pricing-explained', title: 'Transparent Pricing in Kerala Construction', excerpt: 'How BeOnce ensures honesty and no hidden costs.', category: 'Finance' },
  { slug: 'villa-construction-guide', title: 'Luxury Villa Construction Guide', excerpt: 'Designing premium spaces with a focus on luxury and comfort.', category: 'Luxury' },
  { slug: 'permit-process-kerala', title: 'Building Permits & Approvals in Kerala', excerpt: 'Navigating KMBR/KPBR rules for your home.', category: 'Legal' },
  { slug: 'nri-home-construction-tips', title: 'NRI Home Construction Management', excerpt: 'Building your home in Kerala while living abroad.', category: 'NRI' },
  { slug: 'eco-friendly-building-materials', title: 'Eco-friendly Building Materials', excerpt: 'Sustainable choices for a greener home in Kerala.', category: 'Eco' },
  { slug: 'foundation-types-kerala-soil', title: 'Foundation Types for Kerala Soil', excerpt: 'Engineering solutions for different terrains.', category: 'Engineering' },
  { slug: 'interior-design-small-homes', title: 'Interior Design for Small Kerala Homes', excerpt: 'Maximizing space in compact residential plots.', category: 'Design' },
  { slug: 'vastu-shastra-modern-homes', title: 'Vastu Shastra for Modern Boxy Homes', excerpt: 'Merging ancient wisdom with modern architecture.', category: 'Vastu' },
  { slug: 'land-selection-tips', title: 'Land Selection Tips for Home Building', excerpt: 'What to check before buying a plot in Kerala.', category: 'Planning' },
  { slug: 'soil-testing-importance', title: 'Why Soil Testing is Mandatory', excerpt: 'Ensuring structural safety from the ground up.', category: 'Safety' },
  { slug: 'smart-home-features-2024', title: 'Smart Home Features for New Villas', excerpt: 'Integrating technology into your living space.', category: 'Tech' },
  { slug: 'roofing-solutions-tropics', title: 'Roofing Solutions for Tropical Climate', excerpt: 'Keeping your home cool and leak-proof.', category: 'Architecture' },
  { slug: 'kitchen-renovation-trends', title: 'Kitchen Renovation Trends in Kerala', excerpt: 'Transforming your cooking space with modern modular designs.', category: 'Renovation' },
  { slug: 'building-3bhk-3cent-plot', title: '3BHK on a 3 Cent Plot: Is it Possible?', excerpt: 'Creative architectural solutions for tight spaces.', category: 'Compact' },
];