export const servicesList = [
  { title: 'House Construction', slug: 'house-construction-kerala', description: 'Expert residential builders focused on quality and durability.', price: '₹2400.00 / sqft' },
  { title: 'Villa Construction', slug: 'villa-construction-kerala', description: 'Luxury villa projects with custom architectural designs.', price: 'Custom Pricing' },
  { title: '22 Lakhs Package', slug: 'budget-home-construction-kerala', description: 'High-quality living at unbeatable affordable rates.', price: '₹22,00,000.00' },
  { title: 'Turnkey Solutions', slug: 'turnkey-construction-kerala', description: 'Stress-free building from plot to key handover.', price: 'All Inclusive' },
  { title: 'Home Renovation', slug: 'home-renovation-kerala', description: 'Modernize and transform your old home into a new space.', price: 'Per Quote' },
  { title: 'Interior Design', slug: 'interior-design-kerala', description: 'Contemporary interior solutions for modern living.', price: '₹450 / sqft' },
  { title: 'Architectural Planning', slug: 'architectural-planning', description: '2D & 3D planning for your dream home vision.', price: 'Starts ₹15k' },
  { title: 'Structural Engineering', slug: 'structural-engineering', description: 'Safe and robust engineering for all terrains.', price: 'Expert Analysis' },
  { title: 'Landscape Design', slug: 'landscape-design-kerala', description: 'Beautiful gardens and outdoor space planning.', price: 'Custom Quote' },
  { title: 'Kitchen Remodeling', slug: 'kitchen-remodeling', description: 'Upgrade your kitchen to a modern modular setup.', price: 'Starts ₹1.5L' },
  { title: 'Bathroom Renovation', slug: 'bathroom-renovation', description: 'Luxury bathroom upgrades with premium fittings.', price: 'Starts ₹80k' },
  { title: 'Painting & Finishing', slug: 'painting-finishing', description: 'Premium wall finishes and weather protection.', price: '₹22 / sqft' },
  { title: 'Electrical & Plumbing', slug: 'electrical-plumbing', description: 'Reliable utility installations and maintenance.', price: 'Per Point' },
  { title: 'Flooring & Tiling', slug: 'flooring-tiling', description: 'High-quality tiling for a premium floor finish.', price: '₹45 / sqft' },
  { title: 'Smart Home Integration', slug: 'smart-home-integration', description: 'Integrated technology for a modern smart life.', price: 'Custom' },
  { title: 'Vastu Consultancy', slug: 'vastu-consultancy', description: 'Merging ancient wisdom with modern architecture.', price: 'Consultation' },
  { title: 'Building Permits', slug: 'building-permits', description: 'Hassle-free government approvals and paperwork.', price: 'Flat Fee' },
  { title: 'Site Analysis', slug: 'site-analysis-soil-testing', description: 'Soil testing and site safety evaluations.', price: 'Technical' },
  { title: 'NRI Property Management', slug: 'nri-property-management', description: 'Build and manage your home while living abroad.', price: 'Service Fee' },
  { title: 'Eco-friendly Build', slug: 'eco-friendly-construction', description: 'Sustainable construction for a greener Kerala.', price: 'Sustainable' },
  { title: 'Modular Kitchen', slug: 'modular-kitchen-installation', description: 'Quick and stylish modular kitchen setups.', price: 'Premium' },
  { title: 'Commercial Build', slug: 'commercial-construction', description: 'Building modern workspaces and retail outlets.', price: 'Commercial' },
];